// Victory screen with return to map link
// TODO: IMPORT LIBRARIES: REACT, REACT-ROUTER-DOM
// TODO:CR8 FUNCTIONAL VICTORY COMPONENT
// TODO: W/I VICTORY COMPONENT USENAVIGATE()
// TODO: ADD IMG SRC "/clients/backgrounds/codezilla_bkgd.png"
// TODO: NAVIGATE BACK TO THE MAP
// TODO: CREAT A CONTAINER VICTORY-CONTAINER
// TODO: CREATE "VICTORY" HEADER
// TODO: CREATE A VICTORY CONGRATULATORY MESSAGE
// TODO: CREATE A PLAY AGAIN BUTTON
// TODO: EXPORT DEFAULT VICTORY

